### ISSUE TITLE
AUR and Timeshift

### ISSUE THREAD

**Issue by ErickHoward** [sugkiy/ManjarotoArch#13]
I have some questions about the script.

1. How does it deal with AUR packages?
2. Does it wipe Timeshift backups using BTRFS? If I make a backup before running it can I restore the backup afterwards if there are problems?

Thanks

**Comment by sugkiy** [comment]
Lol of course not
Only packages that deal with Manjaro stuff are deleted.
Also would you please look at the script before you file an issue about anything? There is absolutely no part about dealing with btrfs snapshots. Timeshift is a package in the AUR, not a Manjaro-specific package. I use btrfs and zfs myself and deleting packages that aren't related to them won't do anything.
TL;DR: No. Also LOOK AT THE SCRIPT BEFORE ASKING ANYTHING! DO YOU EVEN HAVE AN EYE?

**Comment by sugkiy** [comment]
Ok, I understand that you want to ask something because you have no knowledge of shell scripts and want to ask if your system doesn't get borked.
However I want you to also understand that devs get extremely stressed out while dealing with questions and issues that happen solely because the user didn't RTFM. Please look at the code thoroughly before filing an issue.
